name: deploy_to_staging_bsc

on:
  workflow_dispatch:
  # inputs:
  #   tags:
  #     description: 'Deploy to staging BSC'
  # push:
  #   branches: [staging-bsc]

jobs:
  deploy-staging-bsc:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      
      - name: Install dependencies
        run: |
          npm install

      - name: Run deployment script
        shell: bash
        env:
          ECR_REGISTRY: 842675976501.dkr.ecr.ap-southeast-1.amazonaws.com
        run: |
          npx hardhat run scripts/deploy_bsc.ts --network bsc_testnet

